import type { SessionRecord } from "./session";

/**
 * Minimal JSON Schema representation used for tool inputs.
 */
export type JsonSchema = Record<string, unknown>;

/**
 * Provider-agnostic reasoning intensity requested from the model.
 */
export type ThinkingLevel =
  | "off"
  | "minimal"
  | "low"
  | "medium"
  | "high"
  | "xhigh";

/**
 * Controls whether multiple model-requested tool calls may run concurrently.
 */
export type ToolExecutionMode = "parallel" | "sequential";

/**
 * Async event stream that can also expose a final aggregated result.
 */
export interface ResultStream<TEvent, TResult> extends AsyncIterable<TEvent> {
  /** Resolves to the final result once the stream has completed. */
  result(): Promise<TResult>;
}

/**
 * Token accounting metadata reported by a provider.
 */
export interface TokenUsage {
  /** Tokens consumed by the prompt or request context. */
  input: number;
  /** Tokens generated by the model response. */
  output: number;
  /** Tokens satisfied from a provider-side cache, when available. */
  cacheRead?: number;
  /** Tokens written into a provider-side cache, when available. */
  cacheWrite?: number;
  /** Total token count reported directly by the provider. */
  totalTokens?: number;
  /** Optional monetary cost breakdown associated with the request. */
  cost?: {
    input?: number;
    output?: number;
    cacheRead?: number;
    cacheWrite?: number;
    total?: number;
  };
}

/**
 * Identifies a concrete model selection.
 */
export interface ModelRef {
  /** Model identifier. */
  id: string;
  /** Optional lower-level API variant used to access the model. */
  api?: string;
  /** Optional maximum context window supported by the model. */
  contextWindow?: number;
  /** Indicates whether the model supports explicit reasoning output. */
  reasoning?: boolean;
  /** Additional provider-specific metadata for callers or UIs. */
  metadata?: Record<string, unknown>;
  /** Additional model fields that should flow through untouched. */
  [key: string]: unknown;
}

/**
 * Serializable description of a tool exposed to the model.
 */
export interface LlmToolDefinition {
  /** Stable tool identifier. */
  name: string;
  /** Natural-language description shown to the model. */
  description: string;
  /** JSON Schema describing the tool input payload. */
  inputSchema: JsonSchema;
}

/**
 * Prompt context supplied to an LLM provider.
 */
export interface LlmContext<TMessage = unknown> {
  /** Final system prompt composed for the request. */
  systemPrompt: string;
  /** Provider-native messages included in the request. */
  messages: TMessage[];
  /** Tools available to the model for this request, if any. */
  tools?: LlmToolDefinition[];
}

/**
 * Normalized event model for streaming assistant output.
 */
export type AssistantStreamEvent<TMessage = unknown, TToolCall = unknown> =
  | { type: "start"; partial: TMessage }
  | { type: "text_start"; contentIndex: number; partial: TMessage }
  | {
      type: "text_delta";
      contentIndex: number;
      delta: string;
      partial: TMessage;
    }
  | {
      type: "text_end";
      contentIndex: number;
      content: string;
      partial: TMessage;
    }
  | { type: "thinking_start"; contentIndex: number; partial: TMessage }
  | {
      type: "thinking_delta";
      contentIndex: number;
      delta: string;
      partial: TMessage;
    }
  | {
      type: "thinking_end";
      contentIndex: number;
      content: string;
      partial: TMessage;
    }
  | { type: "toolcall_start"; contentIndex: number; partial: TMessage }
  | {
      type: "toolcall_delta";
      contentIndex: number;
      delta: string;
      partial: TMessage;
    }
  | {
      type: "toolcall_end";
      contentIndex: number;
      toolCall: TToolCall;
      partial: TMessage;
    }
  | { type: "done"; message: TMessage; reason: string }
  | { type: "error"; error: TMessage; reason: "aborted" | "error" };

/**
 * Request payload passed into an LLM provider implementation.
 */
export interface LlmStreamRequest<TMessage = unknown> {
  /** Model selection that should service the request. */
  model: ModelRef;
  /** Fully prepared system prompt, messages, and tool metadata. */
  context: LlmContext<TMessage>;
  /** Optional stable session identifier for provider-side continuity. */
  sessionId?: string;
  /** Requested reasoning intensity for the model. */
  reasoning?: ThinkingLevel;
  /** Upper bound for generated tokens, when supported. */
  maxTokens?: number;
  /** Cancellation signal propagated to provider I/O. */
  signal?: AbortSignal;
  /** Arbitrary caller metadata that provider integrations may use. */
  metadata?: Record<string, unknown>;
}

/**
 * Provider contract used by the runtime agent loop.
 */
export interface LlmProvider<TMessage = unknown> {
  /** Starts streaming a model response for the supplied request. */
  stream(
    request: LlmStreamRequest<TMessage>,
  ): Promise<ResultStream<AssistantStreamEvent<TMessage>, TMessage>>;
}

/**
 * Standardized payload returned by a tool execution.
 */
export interface ToolExecutionResult<TDetails = unknown> {
  /** Content blocks or raw values that should become a tool result message. */
  content: unknown[];
  /** Optional structured details preserved alongside the user-visible content. */
  details?: TDetails;
}

/**
 * Context available to tool implementations at execution time.
 */
export interface AgentToolExecutionContext<
  TMessage = unknown,
  THostContext = unknown,
> {
  /** Active session record, or null for ephemeral runs. */
  session: SessionRecord | null;
  /** Full message history visible to the runtime. */
  messages: TMessage[];
  /** Host-defined ambient context resolved for the current run. */
  hostContext: THostContext;
}

/**
 * Declares a tool that can be surfaced to the model.
 */
export interface ToolDefinition<
  TInput = unknown,
  TDetails = unknown,
  TMessage = unknown,
  THostContext = unknown,
> {
  /** Stable tool identifier used by the model. */
  name: string;
  /** Optional human-friendly label for UIs. */
  label?: string;
  /** Natural-language description describing when the tool should be used. */
  description: string;
  /** JSON Schema for the tool input payload. */
  inputSchema: JsonSchema;
  /** Executes a single tool call and returns normalized output content. */
  execute(args: {
    /** Unique id assigned to the current tool call by the runtime. */
    toolCallId: string;
    /** Parsed tool input matching the declared input schema. */
    input: TInput;
    /** Runtime context visible to the tool implementation. */
    context: AgentToolExecutionContext<TMessage, THostContext>;
    /** Abort signal that is cancelled when the run is aborted. */
    signal: AbortSignal;
    /** Emits partial progress updates while the tool is still running. */
    onUpdate?: (partial: ToolExecutionResult<TDetails>) => void;
  }): Promise<ToolExecutionResult<TDetails>>;
}

/**
 * Context passed into a prompt composer.
 */
export interface PromptComposerContext<
  TState = unknown,
  TMessage = unknown,
  THostContext = unknown,
> {
  /** Active session record, if one is open. */
  session: SessionRecord | null;
  /** Current runtime state snapshot. */
  state: TState;
  /** Selected model for the upcoming request. */
  model: ModelRef;
  /** Tools that will be available to the model. */
  tools: Array<ToolDefinition<unknown, unknown, TMessage, THostContext>>;
  /** Base system prompt configured by the host application. */
  baseSystemPrompt: string;
  /** Host-provided context available to the composer. */
  hostContext: THostContext;
}

/**
 * Builds the final system prompt for a runtime request.
 */
export interface PromptComposer<
  TState = unknown,
  TMessage = unknown,
  THostContext = unknown,
> {
  /** Produces the system prompt that will be sent to the model. */
  compose(
    context: PromptComposerContext<TState, TMessage, THostContext>,
  ): Promise<string>;
}
